### PR TITLE
Moving avg table

### LINKED ISSUE #34: Table for  moving average
Create table and form where user will add their own values for specific ZL

### LINKED ISSUE #35: Function for moving average
Create function that will get array of values as an input and counts  moving average

### PR DESCRIPTION
**Pull request by Spaghettoni**
Table for displaying moving average.

### CODE REVIEW

**Review by Habuon — APPROVED** [review]
pekne za mna je to ok

**Review by ghost — APPROVED** [review]
ok

**Review by Michal-25 — COMMENTED** [review]
Okej

**Comment by Habuon** [comment]
Everything fine

**Pull request merged**
